"""
Investigation finding model.

Represents an intelligence finding generated from passive reconnaissance
observations and their correlations.

A finding is an interpretation layer. It does not replace or duplicate
the original reconnaissance data.
"""

from dataclasses import dataclass, field

from models.correlation import Correlation
from models.evidence import Evidence


@dataclass(slots=True)
class Finding:
    """
    Represents an investigation finding generated by the Intelligence layer.

    The finding contains the information required to explain why a line of
    investigation is relevant while keeping the original reconnaissance
    observations as the source of truth.
    """

    id: str

    title: str

    description: str

    category: str

    confidence: float

    signals: list[str] = field(
        default_factory=list,
    )

    correlations: list[Correlation] = field(
        default_factory=list,
    )

    evidence: list[Evidence] = field(
        default_factory=list,
    )